package ragus.lienty.asynctask;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by Tom on 27/02/2017.
 */

public class StaticData {
    public static final Map<Integer, String> notificationTypes = createMap();

    private static Map<Integer, String> createMap() {

        Map<Integer, String> map = new HashMap<Integer, String>();

        map.put(1, "Legacy");
        map.put(2, "Character deleted");
        map.put(3, "Give medal to character");
        map.put(4, "Alliance maintenance bill");
        map.put(5, "Alliance war declared");
        map.put(6, "Alliance war surrender");
        map.put(7, "Alliance war retracted");
        map.put(8, "Alliance war invalidated by Concord");
        map.put(9, "Bill issued to a character");
        map.put(10, "Bill issued to corporation or alliance");
        map.put(11, "Bill not paid because there's not enough ISK available");
        map.put(12, "Bill, issued by a character, paid");
        map.put(13, "Bill, issued by a corporation or alliance, paid");
        map.put(14, "Bounty claimed");
        map.put(15, "Clone activated");
        map.put(16, "New corp member application");
        map.put(17, "Corp application rejected");
        map.put(18, "Corp application accepted");
        map.put(19, "Corp tax rate changed");
        map.put(20, "Corp news report, typically for shareholders");
        map.put(21, "Player leaves corp");
        map.put(22, "Corp news, new CEO");
        map.put(23, "Corp dividend/liquidation, sent to shareholders");
        map.put(24, "Corp dividend payout, sent to shareholders");
        map.put(25, "Corp vote created");
        map.put(26, "Corp CEO votes revoked during voting");
        map.put(27, "Corp declares war");
        map.put(28, "Corp war has started");
        map.put(29, "Corp surrenders war");
        map.put(30, "Corp retracts war");
        map.put(31, "Corp war invalidated by Concord");
        map.put(32, "Container password retrieval");
        map.put(33, "Contraband or low standings cause an attack or items being confiscated");
        map.put(34, "First ship insurance");
        map.put(35, "Ship destroyed, insurance payed");
        map.put(36, "Insurance contract invalidated/runs out");
        map.put(37, "Sovereignty claim fails (alliance)");
        map.put(38, "Sovereignty claim fails (corporation)");
        map.put(39, "Sovereignty bill late (alliance)");
        map.put(40, "Sovereignty bill late (corporation)");
        map.put(41, "Sovereignty claim lost (alliance)");
        map.put(42, "Sovereignty claim lost (corporation)");
        map.put(43, "Sovereignty claim acquired (alliance)");
        map.put(44, "Sovereignty claim acquired (corporation)");
        map.put(45, "Alliance anchoring alert");
        map.put(46, "Alliance structure turns vulnerable");
        map.put(47, "Alliance structure turns invulnerable");
        map.put(48, "Sovereignty disruptor anchored");
        map.put(49, "Structure won/lost");
        map.put(50, "Corp office lease expiration notice");
        map.put(51, "Clone contract revoked by station manager");
        map.put(52, "Corp member clones moved between stations");
        map.put(53, "Clone contract revoked by station manager");
        map.put(54, "Insurance contract expired");
        map.put(55, "Insurance contract issued");
        map.put(56, "Jump clone destroyed");
        map.put(57, "Jump clone destroyed");
        map.put(58, "Corporation joining factional warfare");
        map.put(59, "Corporation leaving factional warfare");
        map.put(60, "Corporation kicked from factional warfare on startup because of too low standing to the faction");
        map.put(61, "Character kicked from factional warfare on startup because of too low standing to the faction");
        map.put(62, "Corporation in factional warfare warned on startup because of too low standing to the faction");
        map.put(63, "Character in factional warfare warned on startup because of too low standing to the faction");
        map.put(64, "Character loses factional warfare rank");
        map.put(65, "Character gains factional warfare rank");
        map.put(66, "Agent has moved");
        map.put(67, "Mass transaction reversal message");
        map.put(68, "Reimbursement message");
        map.put(69, "Agent locates a character");
        map.put(70, "Research mission becomes available from an agent");
        map.put(71, "Agent mission offer expires");
        map.put(72, "Agent mission times out");
        map.put(73, "Agent offers a storyline mission");
        map.put(74, "Tutorial message sent on character creation");
        map.put(75, "Tower alert");
        map.put(76, "Tower resource alert");
        map.put(77, "Station aggression message");
        map.put(78, "Station state change message");
        map.put(79, "Station conquered message");
        map.put(80, "Station aggression message");
        map.put(81, "Corporation requests joining factional warfare");
        map.put(82, "Corporation requests leaving factional warfare");
        map.put(83, "Corporation withdrawing a request to join factional warfare");
        map.put(84, "Corporation withdrawing a request to leave factional warfare");
        map.put(85, "Corporation liquidation");
        map.put(86, "Territorial Claim Unit under attack");
        map.put(87, "Sovereignty Blockade Unit under attack");
        map.put(88, "Infrastructure Hub under attack");
        map.put(89, "Contact add notification");
        map.put(90, "Contact edit notification");
        map.put(91, "Incursion Completed");
        map.put(92, "Corp Kicked");
        map.put(93, "Customs office has been attacked");
        map.put(94, "Customs office has entered reinforced");
        map.put(95, "Customs office has been transferred");
        map.put(96, "FW Alliance Warning");
        map.put(97, "FW Alliance Kick");
        map.put(98, "AllWarCorpJoined Msg");
        map.put(99, "Ally Joined Defender");
        map.put(100, "Ally Has Joined a War Aggressor");
        map.put(101, "Ally Joined War Ally");
        map.put(102, "New war system: entity is offering assistance in a war.");
        map.put(103, "War Surrender Offer");
        map.put(104, "War Surrender Declined");
        map.put(105, "FacWar LP Payout Kill");
        map.put(106, "FacWar LP Payout Event");
        map.put(107, "FacWar LP Disqualified Eventd");
        map.put(108, "FacWar LP Disqualified Kill");
        map.put(109, "Alliance Contract Cancelled");
        map.put(110, "War Ally Declined Offer");
        map.put(111, "Your Bounty Was Claimed");
        map.put(112, "Bounty placed (Char)");
        map.put(113, "Bounty Placed (Corp)");
        map.put(114, "Bounty Placed (Alliance)");
        map.put(115, "Kill Right Available");
        map.put(116, "Kill right Available Open");
        map.put(117, "Kill Right Earned");
        map.put(118, "Kill right Used");
        map.put(119, "Kill Right Unavailable");
        map.put(120, "Kill Right Unavailable Open");
        map.put(121, "Declare War");
        map.put(122, "Offered Surrender");
        map.put(123, "Accepted Surrender");
        map.put(124, "Made War Mutual");
        map.put(125, "Retracts War");
        map.put(126, "Offered To Ally");
        map.put(127, "Accepted Ally");
        map.put(128, "Character Application Accept");
        map.put(129, "Character Application Reject");
        map.put(130, "Character Application Withdraw");
        map.put(138, "Clone activated");
        map.put(140, "Loss report available");
        map.put(141, "Kill report available");
        map.put(147, "Entosis Link started");
        map.put(148, "Entosis Link enabled a module");
        map.put(149, "Entosis Link disabled a module");
        map.put(131, "DustAppAcceptedMsg ?");
        map.put(132, "DistrictAttacked ?");
        map.put(133, "BattlePunishFriendlyFire ?");
        map.put(135, "BountyESSShared ?");
        map.put(136, "IndustryTeamAuctionWon ?");
        map.put(137, "IndustryTeamAuctionLost ?");
        map.put(139, "Corporation invitation accepted");
        map.put(142, "Corporation application rejected");
        map.put(143, "Friendly fire enable timer started");
        map.put(144, "Friendly fire disable timer started");
        map.put(145, "Friendly fire enable timer completed");
        map.put(146, "Friendly fire disable timer completed");
        map.put(152, "Infrastructure hub bill about to expire");
        map.put(160, "Sovereignty structure reinforced");
        map.put(161, "SovCommandNodeEventStarted ?");
        map.put(162, "Sovereignty structure destroyed");
        map.put(163, "SovStationEnteredFreeport ?");
        map.put(164, "IHubDestroyedByBillFailure ?");
        map.put(134, "BountyESSTaken ?");
        map.put(166, "BuddyConnectContactAdd ?");
        map.put(165, "Alliance capital changed");
        map.put(167, "Sovereignty structure self destruction requested");
        map.put(168, "Sovereignty structure self destruction canceled");
        map.put(169, "Sovereignty structure self destruction completed");
        map.put(181, "Structure fuel alert");
        map.put(182, "Structure anchoring started");
        map.put(183, "Structure unanchoring started");
        map.put(184, "Structure under attack");
        map.put(185, "Structure online");
        map.put(186, "Structure lost shields");
        map.put(187, "Structure lost Armor");
        map.put(188, "Structure destroyed");
        map.put(198, "Structure service offline");
        map.put(199, "Item delivered");
        map.put(201, "StructureCourierContractChanged ?");
        map.put(1012, "OperationFinished ?");
        map.put(1030, "Game time received");
        map.put(1031, "Game time sent");

        return Collections.unmodifiableMap(map);
    }
}

